### ISSUE TITLE
Intent redirection vulnerabity

### ISSUE THREAD

**Issue by okanSerdaroglu** [BKMExpress/BEXAndroidSDK#1]
implementation 'com.bkm:bexandroidsdk:2.1.1'

With this version of your sdk I faced with this issue and my app rejected from Google. When I remove this Sdk, it passed.

![bkm](https://user-images.githubusercontent.com/28345459/103491208-c8418300-4e32-11eb-9c79-53d9d7215b6a.png)

**Comment by bsoykal** [comment]
If you check the readMe section, you could clearly see that, the latest stable version is 2.1.3. Please use the latest one to skip the vulnerability warnings from Google.
